steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/peaceful-fact-418603/adiyodi-assignment2/flask-app/flask-img:latest', '.']
  dir: 'flask-app'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/peaceful-fact-418603/adiyodi-assignment2/flask-app/flask-img:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'flask-app-instance', '--zone', 'us-central1-a']
